export default {
  products: [
    {
      _id: '1',
      name: 'Classic T-Shirt',
      category: 'Shirts',
      image: '/images/t1.jpg',
      price: 30,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 15,
      countInStock: 10,
    },
    {
      _id: '2',
      name: 'Casual Hoodie',
      category: 'Hoodies',
      image: '/images/h1.jpg',
      price: 80,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 7,
      countInStock: 4,
    },
    {
      _id: '3',
      name: 'Sports Joggers',
      category: 'Pants',
      image: '/images/p1.jpg',
      price: 55,
      brand: 'Reebok',
      rating: 4.6,
      numReviews: 12,
      countInStock: 5,
    },
    {
      _id: '4',
      name: 'Running Shoes',
      category: 'Shoes',
      image: '/images/s1.jpg',
      price: 100,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 20,
      countInStock: 8,
    },
  ],
};
